In [0]:
import numpy as np
x = np.array([1,2,3,3,3,3])
x

array([1, 2, 3, 3, 3, 3])

In [0]:
len(x)

6

In [0]:
x[-3]

3

In [0]:
a = np.zeros((2,2))

In [0]:
a

array([[0., 0.],
       [0., 0.]])

In [0]:
b = np.ones((2,2))
b

array([[1., 1.],
       [1., 1.]])

In [0]:
c = a/b

In [0]:
c

array([[0., 0.],
       [0., 0.]])

In [0]:
c = np.random.randint(10, size=5)
c

array([9, 2, 4, 4, 2])

In [0]:
d = np.random.randint(22, size=5)
d

array([21,  6,  3,  7,  3])

In [0]:
d-c

array([12,  4, -1,  3,  1])

In [0]:
a = np.zeros((2,2))

In [0]:
b = np.ones((2,2))

In [0]:
a/b

array([[0., 0.],
       [0., 0.]])

In [0]:
b/a

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([[inf, inf],
       [inf, inf]])

In [0]:
a = np.random.random((2,2))
a

array([[0.41014225, 0.73447443],
       [0.06990826, 0.03067305]])

AttributeError: ignored

In [0]:
np.subtract(a,b)

array([[-0.58985775, -0.26552557],
       [-0.93009174, -0.96932695]])

In [0]:
np.dot(a,b)

array([[1.14461668, 1.14461668],
       [0.10058131, 0.10058131]])

In [0]:
for x in a:
  print(x)

[0.41014225 0.73447443]
[0.06990826 0.03067305]


In [0]:
np.equal(a,b)

array([[False, False],
       [False, False]])

In [0]:
a = np.array([[1,2],[3,4]])

print(np.sum(a))
print(np.sum(a, axis=0))
print(np.sum(a, axis=1))

10
[4 6]
[3 7]


In [0]:
np.array