In [0]:
import numpy as np

a = np.random.random((5,5))

In [2]:
a

array([[3.59447425e-01, 4.56594052e-01, 8.10996360e-02, 1.26120466e-01,
        3.80146452e-01],
       [9.27880205e-01, 5.91135641e-01, 2.53705995e-01, 7.38418670e-01,
        1.79799089e-01],
       [5.35544480e-01, 8.15176092e-01, 6.68769571e-01, 3.53862280e-01,
        5.22022027e-01],
       [9.38565119e-04, 1.84655222e-01, 1.17105135e-01, 8.46118812e-01,
        6.26661499e-01],
       [7.95166519e-01, 5.92259217e-01, 8.87922880e-01, 2.87627789e-01,
        9.65262309e-01]])

In [4]:
a = np.array([[22,13,5,27], [5,20,9,13], [16,19,1,15], [9,0,16,19]])
b = np.array([[10,5,26,27], [5,21,19,8], [20,22,22,18], [20,27,3,7]])

a
b

array([[10,  5, 26, 27],
       [ 5, 21, 19,  8],
       [20, 22, 22, 18],
       [20, 27,  3,  7]])

In [5]:
a+b

array([[32, 18, 31, 54],
       [10, 41, 28, 21],
       [36, 41, 23, 33],
       [29, 27, 19, 26]])

In [6]:
a-b

array([[ 12,   8, -21,   0],
       [  0,  -1, -10,   5],
       [ -4,  -3, -21,  -3],
       [-11, -27,  13,  12]])

In [21]:
print(a*b)
print(np.dot(b,a))

[[220  65 130 729]
 [ 25 420 171 104]
 [320 418  22 270]
 [180   0  48 133]]
[[ 904  724  553 1238]
 [ 591  846  361  845]
 [1064 1118  608 1498]
 [ 686  857  458 1069]]


In [8]:
a/b

array([[2.2       , 2.6       , 0.19230769, 1.        ],
       [1.        , 0.95238095, 0.47368421, 1.625     ],
       [0.8       , 0.86363636, 0.04545455, 0.83333333],
       [0.45      , 0.        , 5.33333333, 2.71428571]])

In [11]:
c = np.array([24,3,17,7,11,2,21,2,24,18,3,11,14,25,2,20])
d = np.array([3,15,24,22,19,24,4,29,6,3,20,1,11,25,26,6])

c+d

array([27, 18, 41, 29, 30, 26, 25, 31, 30, 21, 23, 12, 25, 50, 28, 26])

In [12]:
c-d

array([ 21, -12,  -7, -15,  -8, -22,  17, -27,  18,  15, -17,  10,   3,
         0, -24,  14])

In [13]:
c*d

array([ 72,  45, 408, 154, 209,  48,  84,  58, 144,  54,  60,  11, 154,
       625,  52, 120])

In [23]:
np.dot(c,d)

2298

In [15]:
a+10

array([[32, 23, 15, 37],
       [15, 30, 19, 23],
       [26, 29, 11, 25],
       [19, 10, 26, 29]])

In [17]:
b+10

array([[20, 15, 36, 37],
       [15, 31, 29, 18],
       [30, 32, 32, 28],
       [30, 37, 13, 17]])

In [18]:
c+15

array([39, 18, 32, 22, 26, 17, 36, 17, 39, 33, 18, 26, 29, 40, 17, 35])

In [19]:
d+15

array([18, 30, 39, 37, 34, 39, 19, 44, 21, 18, 35, 16, 26, 40, 41, 21])

In [25]:
print('#13')
((2*a)+(2*b))

#13


array([[ 64,  36,  62, 108],
       [ 20,  82,  56,  42],
       [ 72,  82,  46,  66],
       [ 58,  54,  38,  52]])

In [26]:
print('#14')
((a+b)*3)

#14


array([[ 96,  54,  93, 162],
       [ 30, 123,  84,  63],
       [108, 123,  69,  99],
       [ 87,  81,  57,  78]])

In [27]:
print('#15')
((a-b+a-b+b)*4)

#15


array([[ 136,   84,  -64,  108],
       [  20,   76,   -4,   72],
       [  48,   64,  -80,   48],
       [  -8, -108,  116,  124]])